language: java

jdk:
  - oraclejdk7

services: mysql

install:
  - cd docs
  - cd jars
  - mvn install:install-file -DgroupId=ojdbc -DartifactId=ojdbc -Dpackaging=jar -Dversion=6 -Dfile=ojdbc-6.jar -DgeneratePom=true
  - cd..
  - cd..
  - cd trunk
  - mvn install -DskipTests=true

before_script:
  - mysql -e 'create database tpcs;'

script:
  - mvn cobertura:cobertura coveralls:report

