language: java

jdk:
  - oraclejdk7

services: mysql

install:
  - cd docs/jars
  - mvn install:install-file -DgroupId=ojdbc -DartifactId=ojdbc -Dpackaging=jar -Dversion=6 -Dfile=ojdbc-6.jar -DgeneratePom=true
  - cd ../../
  - cd trunk/tpcs-employee/src/main/resources
  - mv ci/travis-ci.properties application.properties
  - cd ../../../../
  - mvn install -DskipTests=true

before_script:
  - mysql -e 'create database tpcs;'

script:
  - mvn cobertura:cobertura coveralls:report
  - cd tpcs-employee
  - mvn verify -DskipTests=true
